// WARNING: This is a mock aws-exports file for development only.
// Replace with your actual aws-exports.ts generated by AWS Amplify CLI.

const awsExports = {
  aws_project_region: "us-east-1",
  aws_cognito_region: "us-east-1",
  aws_user_pools_id: process.env.NEXT_PUBLIC_AWS_COGNITO_USER_POOL_ID,
  aws_user_pools_web_client_id: process.env.NEXT_PUBLIC_AWS_COGNITO_USER_POOL_CLIENT_ID,
  oauth: {}, // Optional: Fill this in if you're using social login
};

export default awsExports;
